DROP TABLE Codes;
DROP TABLE Translations;
DROP TABLE SiteVisits;

CREATE TABLE IF NOT EXISTS Codes(
	id INTEGER PRIMARY KEY,
	code TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Translations(
	id INTEGER PRIMARY KEY,
	trans TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SiteVisits(
	id INTEGER PRIMARY KEY,
	ip TEXT NOT NULL,
	dateVisited DATETIME DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO Codes (code) VALUES ('AA');
INSERT INTO Translations (trans) VALUES ('To the affected area');
INSERT INTO Codes (code) VALUES ('AB');
INSERT INTO Translations (trans) VALUES ('Both');
INSERT INTO Codes (code) VALUES ('AC');
INSERT INTO Translations (trans) VALUES ('Before a meal');
INSERT INTO Codes (code) VALUES ('AD');
INSERT INTO Translations (trans) VALUES ('Right ear');
INSERT INTO Codes (code) VALUES ('ADM');
INSERT INTO Translations (trans) VALUES ('Administer');
INSERT INTO Codes (code) VALUES ('AEA');
INSERT INTO Translations (trans) VALUES ('In affected ear(s)');
INSERT INTO Codes (code) VALUES ('AEY');
INSERT INTO Translations (trans) VALUES ('In affected eye(s)');
INSERT INTO Codes (code) VALUES ('AIDO');
INSERT INTO Translations (trans) VALUES ('After initial dose');
INSERT INTO Codes (code) VALUES ('ALT');
INSERT INTO Translations (trans) VALUES ('Alternate');
INSERT INTO Codes (code) VALUES ('AMP');
INSERT INTO Translations (trans) VALUES ('Ampule');
INSERT INTO Codes (code) VALUES ('AMT');
INSERT INTO Translations (trans) VALUES ('Amount');
INSERT INTO Codes (code) VALUES ('AOS');
INSERT INTO Translations (trans) VALUES ('At onset');
INSERT INTO Codes (code) VALUES ('APL');
INSERT INTO Translations (trans) VALUES ('Applicatorsful');
INSERT INTO Codes (code) VALUES ('APP');
INSERT INTO Translations (trans) VALUES ('Apply');
INSERT INTO Codes (code) VALUES ('APR');
INSERT INTO Translations (trans) VALUES ('Apply to rash');
INSERT INTO Codes (code) VALUES ('APS');
INSERT INTO Translations (trans) VALUES ('Applicatorsful');
INSERT INTO Codes (code) VALUES ('ASD');
INSERT INTO Translations (trans) VALUES ('Apply sparingly with each diaper change');
INSERT INTO Codes (code) VALUES ('ATC');
INSERT INTO Translations (trans) VALUES ('Around the clock');
INSERT INTO Codes (code) VALUES ('ATN');
INSERT INTO Translations (trans) VALUES ('At night');
INSERT INTO Codes (code) VALUES ('AU');
INSERT INTO Translations (trans) VALUES ('Both ears');
INSERT INTO Codes (code) VALUES ('AVN');
INSERT INTO Translations (trans) VALUES ('Use 1 ampule via nebulizer');
INSERT INTO Codes (code) VALUES ('B');
INSERT INTO Translations (trans) VALUES ('Before');
INSERT INTO Codes (code) VALUES ('BED');
INSERT INTO Translations (trans) VALUES ('Bedtime');
INSERT INTO Codes (code) VALUES ('BID');
INSERT INTO Translations (trans) VALUES ('Twice daily');
INSERT INTO Codes (code) VALUES ('BM');
INSERT INTO Translations (trans) VALUES ('Bowel movement');
INSERT INTO Codes (code) VALUES ('BP');
INSERT INTO Translations (trans) VALUES ('Blood pressure');
INSERT INTO Codes (code) VALUES ('BRE');
INSERT INTO Translations (trans) VALUES ('Breakfast');
INSERT INTO Codes (code) VALUES ('C');
INSERT INTO Translations (trans) VALUES ('Capsule');
INSERT INTO Codes (code) VALUES ('CS');
INSERT INTO Translations (trans) VALUES ('Capsules');
INSERT INTO Codes (code) VALUES ('CFL');
INSERT INTO Translations (trans) VALUES ('Capful');
INSERT INTO Codes (code) VALUES ('CNC');
INSERT INTO Translations (trans) VALUES ('Cough and congestion');
INSERT INTO Codes (code) VALUES ('CNTS');
INSERT INTO Translations (trans) VALUES ('Contents of 1 packet');
INSERT INTO Codes (code) VALUES ('COG');
INSERT INTO Translations (trans) VALUES ('Congestion');
INSERT INTO Codes (code) VALUES ('CONS');
INSERT INTO Translations (trans) VALUES ('Consecutive');
INSERT INTO Codes (code) VALUES ('COU');
INSERT INTO Translations (trans) VALUES ('For cough');
INSERT INTO Codes (code) VALUES ('CRU');
INSERT INTO Translations (trans) VALUES ('Crush');
INSERT INTO Codes (code) VALUES ('CSW');
INSERT INTO Translations (trans) VALUES ('Chew and swallow');
INSERT INTO Codes (code) VALUES ('D');
INSERT INTO Translations (trans) VALUES ('Daily');
INSERT INTO Codes (code) VALUES ('DAPP');
INSERT INTO Translations (trans) VALUES ('Dental appointment');
INSERT INTO Codes (code) VALUES ('DH');
INSERT INTO Translations (trans) VALUES ('Diarrhea');
INSERT INTO Codes (code) VALUES ('DID');
INSERT INTO Translations (trans) VALUES ('Two or three times daily for weight loss');
INSERT INTO Codes (code) VALUES ('DIS');
INSERT INTO Translations (trans) VALUES ('Dissolve');
INSERT INTO Codes (code) VALUES ('DNC');
INSERT INTO Translations (trans) VALUES ('Take four capsules 1 hour before dental appointment');
INSERT INTO Codes (code) VALUES ('DNT');
INSERT INTO Translations (trans) VALUES ('Take four tablets 1 hour before dental appointment');
INSERT INTO Codes (code) VALUES ('DPS');
INSERT INTO Translations (trans) VALUES ('Droppersful');
INSERT INTO Codes (code) VALUES ('DR');
INSERT INTO Translations (trans) VALUES ('Discard remainder');
INSERT INTO Codes (code) VALUES ('DRK');
INSERT INTO Translations (trans) VALUES ('Drink');
INSERT INTO Codes (code) VALUES ('DRP');
INSERT INTO Translations (trans) VALUES ('Dropperful');
INSERT INTO Codes (code) VALUES ('EC');
INSERT INTO Translations (trans) VALUES ('Each cheek');
INSERT INTO Codes (code) VALUES ('EVE');
INSERT INTO Translations (trans) VALUES ('Evening');
INSERT INTO Codes (code) VALUES ('EXT');
INSERT INTO Translations (trans) VALUES ('Externally');
INSERT INTO Codes (code) VALUES ('FEV');
INSERT INTO Translations (trans) VALUES ('As needed for fever');
INSERT INTO Codes (code) VALUES ('FEVP');
INSERT INTO Translations (trans) VALUES ('As needed for fever and pain');
INSERT INTO Codes (code) VALUES ('FID');
INSERT INTO Translations (trans) VALUES ('Five times daily');
INSERT INTO Codes (code) VALUES ('FPD');
INSERT INTO Translations (trans) VALUES ('Follow package directions');
INSERT INTO Codes (code) VALUES ('FRI');
INSERT INTO Translations (trans) VALUES ('Friday');
INSERT INTO Codes (code) VALUES ('G');
INSERT INTO Translations (trans) VALUES ('Give');
INSERT INTO Codes (code) VALUES ('GEF');
INSERT INTO Translations (trans) VALUES ('Generic equivalent for');
INSERT INTO Codes (code) VALUES ('GEQ');
INSERT INTO Translations (trans) VALUES ('Generic equivalent to');
INSERT INTO Codes (code) VALUES ('GF');
INSERT INTO Translations (trans) VALUES ('Generic for');
INSERT INTO Codes (code) VALUES ('GSM');
INSERT INTO Translations (trans) VALUES ('Generic substitution made');
INSERT INTO Codes (code) VALUES ('GTB');
INSERT INTO Translations (trans) VALUES ('Gtube');
INSERT INTO Codes (code) VALUES ('GTS');
INSERT INTO Translations (trans) VALUES ('Drops');
INSERT INTO Codes (code) VALUES ('GTT');
INSERT INTO Translations (trans) VALUES ('Drop');
INSERT INTO Codes (code) VALUES ('H');
INSERT INTO Translations (trans) VALUES ('Hours');
INSERT INTO Codes (code) VALUES ('HA');
INSERT INTO Translations (trans) VALUES ('Headache');
INSERT INTO Codes (code) VALUES ('HS');
INSERT INTO Translations (trans) VALUES ('At bedtime');
INSERT INTO Codes (code) VALUES ('I');
INSERT INTO Translations (trans) VALUES ('Insert');
INSERT INTO Codes (code) VALUES ('IEN');
INSERT INTO Translations (trans) VALUES ('In each nostril');
INSERT INTO Codes (code) VALUES ('IM');
INSERT INTO Translations (trans) VALUES ('In the muscle');
INSERT INTO Codes (code) VALUES ('IMM');
INSERT INTO Translations (trans) VALUES ('Immediately');
INSERT INTO Codes (code) VALUES ('INJ');
INSERT INTO Translations (trans) VALUES ('Inject');
INSERT INTO Codes (code) VALUES ('INL');
INSERT INTO Translations (trans) VALUES ('Inhale');
INSERT INTO Codes (code) VALUES ('INT');
INSERT INTO Translations (trans) VALUES ('Instill');
INSERT INTO Codes (code) VALUES ('IVB');
INSERT INTO Translations (trans) VALUES ('Insert one applicatorful vaginally at bedtime');
INSERT INTO Codes (code) VALUES ('IVS');
INSERT INTO Translations (trans) VALUES ('Insert one suppository vaginally at bedtime');
INSERT INTO Codes (code) VALUES ('JTB');
INSERT INTO Translations (trans) VALUES ('Jtube');
INSERT INTO Codes (code) VALUES ('LEA');
INSERT INTO Translations (trans) VALUES ('In the left ear');
INSERT INTO Codes (code) VALUES ('LEY');
INSERT INTO Translations (trans) VALUES ('In the left eye');
INSERT INTO Codes (code) VALUES ('LOZ');
INSERT INTO Translations (trans) VALUES ('Lozenge');
INSERT INTO Codes (code) VALUES ('LQ');
INSERT INTO Translations (trans) VALUES ('Liquid');
INSERT INTO Codes (code) VALUES ('MCD');
INSERT INTO Translations (trans) VALUES ('May cause drowsiness');
INSERT INTO Codes (code) VALUES ('MDD');
INSERT INTO Translations (trans) VALUES ('Maximum daily dose is');
INSERT INTO Codes (code) VALUES ('MIN');
INSERT INTO Translations (trans) VALUES ('Minutes');
INSERT INTO Codes (code) VALUES ('MON');
INSERT INTO Translations (trans) VALUES ('Monday');
INSERT INTO Codes (code) VALUES ('MWF');
INSERT INTO Translations (trans) VALUES ('Monday, Wednesday, Friday');
INSERT INTO Codes (code) VALUES ('MX');
INSERT INTO Translations (trans) VALUES ('Mix');
INSERT INTO Codes (code) VALUES ('MXC');
INSERT INTO Translations (trans) VALUES ('Mix 1 capful');
INSERT INTO Codes (code) VALUES ('N');
INSERT INTO Translations (trans) VALUES ('For nausea');
INSERT INTO Codes (code) VALUES ('NEB');
INSERT INTO Translations (trans) VALUES ('Nebulizer');
INSERT INTO Codes (code) VALUES ('NER');
INSERT INTO Translations (trans) VALUES ('For nerves');
INSERT INTO Codes (code) VALUES ('NGTB');
INSERT INTO Translations (trans) VALUES ('Ng-tube');
INSERT INTO Codes (code) VALUES ('NM3');
INSERT INTO Translations (trans) VALUES ('No more than 3,000mg of acetaminophen daily');
INSERT INTO Codes (code) VALUES ('NM4');
INSERT INTO Translations (trans) VALUES ('No more than 4,000mg of acetaminophen daily');
INSERT INTO Codes (code) VALUES ('NOS');
INSERT INTO Translations (trans) VALUES ('Nostril');
INSERT INTO Codes (code) VALUES ('NTS');
INSERT INTO Translations (trans) VALUES ('Nights');
INSERT INTO Codes (code) VALUES ('NV');
INSERT INTO Translations (trans) VALUES ('For nausea and vomiting');
INSERT INTO Codes (code) VALUES ('OC');
INSERT INTO Translations (trans) VALUES ('1 d for a full cycle. Stop for 1 week, then repeat');
INSERT INTO Codes (code) VALUES ('OD');
INSERT INTO Translations (trans) VALUES ('Right eye');
INSERT INTO Codes (code) VALUES ('OES');
INSERT INTO Translations (trans) VALUES ('On an empty stomach');
INSERT INTO Codes (code) VALUES ('OS');
INSERT INTO Translations (trans) VALUES ('Left Eye');
INSERT INTO Codes (code) VALUES ('OU');
INSERT INTO Translations (trans) VALUES ('Both eyes');
INSERT INTO Codes (code) VALUES ('P');
INSERT INTO Translations (trans) VALUES ('For pain');
INSERT INTO Codes (code) VALUES ('PA');
INSERT INTO Translations (trans) VALUES ('Patch');
INSERT INTO Codes (code) VALUES ('PC');
INSERT INTO Translations (trans) VALUES ('After a meal');
INSERT INTO Codes (code) VALUES ('PFS');
INSERT INTO Translations (trans) VALUES ('Puffs');
INSERT INTO Codes (code) VALUES ('PO');
INSERT INTO Translations (trans) VALUES ('By mouth');
INSERT INTO Codes (code) VALUES ('PRA');
INSERT INTO Translations (trans) VALUES ('As needed for anxiety');
INSERT INTO Codes (code) VALUES ('PRF');
INSERT INTO Translations (trans) VALUES ('As needed for');
INSERT INTO Codes (code) VALUES ('PRN');
INSERT INTO Translations (trans) VALUES ('As needed');
INSERT INTO Codes (code) VALUES ('Q');
INSERT INTO Translations (trans) VALUES ('Every');
INSERT INTO Codes (code) VALUES ('QAF');
INSERT INTO Translations (trans) VALUES ('Every afternoon');
INSERT INTO Codes (code) VALUES ('QAM');
INSERT INTO Translations (trans) VALUES ('Every Morning');
INSERT INTO Codes (code) VALUES ('QD');
INSERT INTO Translations (trans) VALUES ('Every Day');
INSERT INTO Codes (code) VALUES ('QDW');
INSERT INTO Translations (trans) VALUES ('4 days a week');
INSERT INTO Codes (code) VALUES ('QHS');
INSERT INTO Translations (trans) VALUES ('Every night at bedtime');
INSERT INTO Codes (code) VALUES ('QID');
INSERT INTO Translations (trans) VALUES ('Four times daily');
INSERT INTO Codes (code) VALUES ('QOD');
INSERT INTO Translations (trans) VALUES ('Every other day');
INSERT INTO Codes (code) VALUES ('QPM');
INSERT INTO Translations (trans) VALUES ('Every evening');
INSERT INTO Codes (code) VALUES ('R');
INSERT INTO Translations (trans) VALUES ('Rectal');
INSERT INTO Codes (code) VALUES ('REA');
INSERT INTO Translations (trans) VALUES ('In the right ear');
INSERT INTO Codes (code) VALUES ('REC');
INSERT INTO Translations (trans) VALUES ('Rectally');
INSERT INTO Codes (code) VALUES ('REY');
INSERT INTO Translations (trans) VALUES ('In the right eye');
INSERT INTO Codes (code) VALUES ('RF');
INSERT INTO Translations (trans) VALUES ('Refrigerate');
INSERT INTO Codes (code) VALUES ('RVN');
INSERT INTO Translations (trans) VALUES ('Use 1 respule via nebulizer');
INSERT INTO Codes (code) VALUES ('SAS');
INSERT INTO Translations (trans) VALUES ('Swish and Swallow');
INSERT INTO Codes (code) VALUES ('SAT');
INSERT INTO Translations (trans) VALUES ('Saturday');
INSERT INTO Codes (code) VALUES ('SC');
INSERT INTO Translations (trans) VALUES ('Under the skin');
INSERT INTO Codes (code) VALUES ('SLP');
INSERT INTO Translations (trans) VALUES ('Sleep');
INSERT INTO Codes (code) VALUES ('SML');
INSERT INTO Translations (trans) VALUES ('Small');
INSERT INTO Codes (code) VALUES ('SND');
INSERT INTO Translations (trans) VALUES ('Sunday');
INSERT INTO Codes (code) VALUES ('SOA');
INSERT INTO Translations (trans) VALUES ('Soak');
INSERT INTO Codes (code) VALUES ('SOB');
INSERT INTO Translations (trans) VALUES ('Shortness of breath');
INSERT INTO Codes (code) VALUES ('SPR');
INSERT INTO Translations (trans) VALUES ('Spray');
INSERT INTO Codes (code) VALUES ('SPS');
INSERT INTO Translations (trans) VALUES ('Suppositories');
INSERT INTO Codes (code) VALUES ('SQ');
INSERT INTO Translations (trans) VALUES ('Subcutcaneous');
INSERT INTO Codes (code) VALUES ('SS');
INSERT INTO Translations (trans) VALUES ('ONE-Half');
INSERT INTO Codes (code) VALUES ('SUP');
INSERT INTO Translations (trans) VALUES ('Suppository');
INSERT INTO Codes (code) VALUES ('SW');
INSERT INTO Translations (trans) VALUES ('Shake liquid well');
INSERT INTO Codes (code) VALUES ('SWR');
INSERT INTO Translations (trans) VALUES ('Shake well and refrigerate');
INSERT INTO Codes (code) VALUES ('T');
INSERT INTO Translations (trans) VALUES ('Tablet');
INSERT INTO Codes (code) VALUES ('TS');
INSERT INTO Translations (trans) VALUES ('Tablets');
INSERT INTO Codes (code) VALUES ('TAT');
INSERT INTO Translations (trans) VALUES ('Until all taken');
INSERT INTO Codes (code) VALUES ('TAY');
INSERT INTO Translations (trans) VALUES ('Today');
INSERT INTO Codes (code) VALUES ('TBL');
INSERT INTO Translations (trans) VALUES ('Tablespoonful');
INSERT INTO Codes (code) VALUES ('TDW');
INSERT INTO Translations (trans) VALUES ('3 days a week');
INSERT INTO Codes (code) VALUES ('TEA');
INSERT INTO Translations (trans) VALUES ('Teaspoonful');
INSERT INTO Codes (code) VALUES ('TES');
INSERT INTO Translations (trans) VALUES ('Teaspoonsful');
INSERT INTO Codes (code) VALUES ('THUR');
INSERT INTO Translations (trans) VALUES ('Thursday');
INSERT INTO Codes (code) VALUES ('TID');
INSERT INTO Translations (trans) VALUES ('Three times daily');
INSERT INTO Codes (code) VALUES ('TK');
INSERT INTO Translations (trans) VALUES ('Take');
INSERT INTO Codes (code) VALUES ('TLS');
INSERT INTO Translations (trans) VALUES ('Tablespoonsful');
INSERT INTO Codes (code) VALUES ('TNT');
INSERT INTO Translations (trans) VALUES ('One tablet under tongue as needed for chest pain');
INSERT INTO Codes (code) VALUES ('TUE');
INSERT INTO Translations (trans) VALUES ('Tuesday');
INSERT INTO Codes (code) VALUES ('TW');
INSERT INTO Translations (trans) VALUES ('One tablet in water');
INSERT INTO Codes (code) VALUES ('U');
INSERT INTO Translations (trans) VALUES ('Use');
INSERT INTO Codes (code) VALUES ('UNI');
INSERT INTO Translations (trans) VALUES ('Units');
INSERT INTO Codes (code) VALUES ('UNT');
INSERT INTO Translations (trans) VALUES ('Under the tongue');
INSERT INTO Codes (code) VALUES ('UNW');
INSERT INTO Translations (trans) VALUES ('Unwrap');
INSERT INTO Codes (code) VALUES ('UTD');
INSERT INTO Translations (trans) VALUES ('As directed');
INSERT INTO Codes (code) VALUES ('VA');
INSERT INTO Translations (trans) VALUES ('Vaginal');
INSERT INTO Codes (code) VALUES ('VAG');
INSERT INTO Translations (trans) VALUES ('In the vagina');
INSERT INTO Codes (code) VALUES ('VOM');
INSERT INTO Translations (trans) VALUES ('Vomiting');
INSERT INTO Codes (code) VALUES ('VVN');
INSERT INTO Translations (trans) VALUES ('Use 1 vial via nebulizer');
INSERT INTO Codes (code) VALUES ('WA');
INSERT INTO Translations (trans) VALUES ('While awake');
INSERT INTO Codes (code) VALUES ('WC');
INSERT INTO Translations (trans) VALUES ('With meals');
INSERT INTO Codes (code) VALUES ('WED');
INSERT INTO Translations (trans) VALUES ('Wednesday');
INSERT INTO Codes (code) VALUES ('WF');
INSERT INTO Translations (trans) VALUES ('With food');
INSERT INTO Codes (code) VALUES ('WFJ');
INSERT INTO Translations (trans) VALUES ('With fruit juice');
INSERT INTO Codes (code) VALUES ('WHZ');
INSERT INTO Translations (trans) VALUES ('Wheezing');
INSERT INTO Codes (code) VALUES ('WKS');
INSERT INTO Translations (trans) VALUES ('Weeks');
INSERT INTO Codes (code) VALUES ('WOJ');
INSERT INTO Translations (trans) VALUES ('With orange juice');
INSERT INTO Codes (code) VALUES ('XD');
INSERT INTO Translations (trans) VALUES ('Times daily');